apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-2
  name: mongodb-2
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-2
    spec:
      containers:
      - args:
        - mongod
        - --shardsvr
        - --replSet
        - mongodbshard-1
        image: mongo:3
        name: mongodb-2
        resources:
          requests:
            memory: 8Gi
        resources: 
          limits:
            memory: 9Gi
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-2-disk
      restartPolicy: Always
      volumes:
      - name: mongodb-2-disk
        gcePersistentDisk:
          pdName: mongodb-2
          fsType: ext4
status: {}
