apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-router
  name: mongodb-router
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-router
    spec:
      containers:
      - args:
        - mongos
        - --configdb
        - mongodbcfg/mongodb-cfg-1:27019,mongodb-cfg-2:27019,mongodb-cfg-3:27019
        image: mongo:3
        name: mongodb-router
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
