apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-5
  name: mongodb-5
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-5
    spec:
      containers:
      - args:
        - mongod
        - --shardsvr
        - --replSet
        - mongodbshard-2
        image: mongo:3
        name: mongodb-5
        resources:
          limits:
            memory: 9Gi
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-5-disk
      restartPolicy: Always
      volumes:
      - name: mongodb-5-disk
        gcePersistentDisk:
          pdName: mongodb-5
          fsType: ext4
status: {}
