apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-cfg-3
  name: mongodb-cfg-3
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-cfg-3
    spec:
      containers:
      - args:
        - mongod
        - --configsvr
        - --replSet
        - mongodbcfg
        image: mongo:3
        name: mongodb-cfg-3
        resources: {}
        # volumeMounts:
        # - mountPath: /data/db
        #   name: mongodb-cfg-3-disk
      restartPolicy: Always
      # volumes:
      # - name: mongodb-cfg-3-disk
      #   # hostPath:
      #   #   # directory location on host
      #     # path: /mnt/data/mongo-cfg-3
      #   gcePersistentDisk:
      #     pdName: mongodb-cfg-3
      #     fsType: ext4
status: {}
