apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-6
  name: mongodb-6
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-6
    spec:
      containers:
      - args:
        - mongod
        - --shardsvr
        - --replSet
        - mongodbshard-2
        image: mongo:3
        name: mongodb-6
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-6-disk
      restartPolicy: Always
      volumes:
      - name: mongodb-6-disk
        gcePersistentDisk:
          pdName: mongodb-6
          fsType: ext4
status: {}
