apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.service.type: LoadBalancer
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-router
  name: mongodb-router
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-router
    spec:
      containers:
      - args:
        - mongos
        - --configdb
        - mongodbcfg/mongodb-cfg-1:27019,mongodb-cfg-2:27019,mongodb-cfg-3:27019
        image: mongo:3
        name: mongodb-router
        resources: {}
        # volumeMounts:
        # - mountPath: /data/db
        #   name: mongodb-router-disk
      restartPolicy: Always
      volumes:
      # - name: mongodb-router-disk
        # hostPath:
        #   # directory location on host
        #   path: /mnt/data/mongo-router
        # gcePersistentDisk:
        #   pdName: mongodb-router
        #   fsType: ext4
status: {}
