apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-3
  name: mongodb-3
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-3
    spec:
      containers:
      - args:
        - mongod
        - --shardsvr
        - --replSet
        - mongodbshard-1
        - --wiredTigerCacheSizeGB
        - "8"
        image: mongo:3
        name: mongodb-3
        resources:
          requests:
            memory: '2Gi'
          limits:
            memory: "9663676416"
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-3-disk
      restartPolicy: Always
      volumes:
      - name: mongodb-3-disk
        gcePersistentDisk:
          pdName: mongodb-3
          fsType: ext4
status: {}
