apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-cfg-3
  name: mongodb-cfg-3
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-cfg-3
    spec:
      containers:
      - args:
        - mongod
        - --configsvr
        - --replSet
        - mongodbcfg
        - --wiredTigerCacheSizeGB
        - "8"
        image: mongo:3
        name: mongodb-cfg-3
        resources:
          requests:
            memory: '2Gi'
          limits:
            memory: "9663676416"
        volumeMounts:
        - mountPath: /data
          name: mongodb-cfg-3-disk
      restartPolicy: Always
      volumes:
      - name: mongodb-cfg-3-disk
        gcePersistentDisk:
          pdName: mongodb-cfg-3
          fsType: ext4
status: {}
