apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-1
  name: mongodb-1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-1
    spec:
      containers:
      - args:
        - mongod
        - --shardsvr
        - --replSet
        - mongodbshard-1
        image: mongo:3
        resources:
          requests:
            memory: 8Gi
        name: mongodb-1
        resources:
          limits:
            memory: 9Gi
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-1-disk
      restartPolicy: Always
      volumes:
      - name: mongodb-1-disk
        gcePersistentDisk:
          pdName: mongodb-1
          fsType: ext4
status: {}
