version: '2'
services:
  mongodb-cfg-1:
    image: mongo:3
    expose:
      - 27019
    command: "mongod --configsvr --replSet mongodbcfg --wiredTigerCacheSizeGB 5"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo-cfg-1:/data/db
      - ./mnt/configdb/mongo-cfg-1:/data/configdb
    links:
      - mongodb-router
      - mongodb-1
      - mongodb-cfg-2
      - mongodb-cfg-3

    networks:
      shopline:
  mongodb-cfg-2:
    image: mongo:3
    expose:
      - 27019
    command: "mongod --configsvr --replSet mongodbcfg --wiredTigerCacheSizeGB 5"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo-cfg-2:/data/db
      - ./mnt/configdb/mongo-cfg-2:/data/configdb
    links:
      - mongodb-router
      - mongodb-1
    networks:
      shopline:
  mongodb-cfg-3:
    image: mongo:3
    expose:
      - 27019
    command: "mongod --configsvr --replSet mongodbcfg --wiredTigerCacheSizeGB 5"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo-cfg-3:/data/db
      - ./mnt/configdb/mongo-cfg-3:/data/configdb
    links:
      - mongodb-router
      - mongodb-1
    networks:
      shopline:
  mongodb-1:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-1 --wiredTigerCacheSizeGB 5"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo1:/data/db
      - ./mnt/configdb/mongo1:/data/configdb
    networks:
      shopline:
  mongodb-2:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-1 --wiredTigerCacheSizeGB 5"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo2:/data/db
      - ./mnt/configdb/mongo2:/data/configdb
    networks:
      shopline:
  mongodb-3:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-1 --wiredTigerCacheSizeGB 5"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo3:/data/db
      - ./mnt/configdb/mongo3:/data/configdb
    networks:
      shopline:
  mongodb-4:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-2 --wiredTigerCacheSizeGB 5"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo4:/data/db
      - ./mnt/configdb/mongo4:/data/configdb
    networks:
      shopline:
  mongodb-5:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-2 --wiredTigerCacheSizeGB 5"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo5:/data/db
      - ./mnt/configdb/mongo5:/data/configdb
    networks:
      shopline:
  mongodb-6:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-2 --wiredTigerCacheSizeGB 5"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo6:/data/db
      - ./mnt/configdb/mongo6:/data/configdb
    networks:
      shopline:
  mongodb-router:
    image: mongo:3
    ports:
      - 27017:27017
    command: "mongos --configdb mongodbcfg/mongodb-cfg-1:27019,mongodb-cfg-2:27019,mongodb-cfg-3:27019"
    mem_limit: 9G
    restart: always
    volumes:
      - ./mnt/data/mongo-router:/data/db
      - ./mnt/configdb/mongo-router:/data/configdb
    networks:
      shopline:
        aliases:
          - dev-mongo
    labels:
      kompose.service.type: LoadBalancer
  redis:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./mnt/data/redis:/data
networks:
  shopline:
