version: '2'
services:
  mongodb-cfg-1:
    image: mongo:3
    expose:
      - 27019
    command: "mongod --configsvr --replSet mongodbcfg"
    links:
      - mongodb-router
      - mongodb-1
      - mongodb-cfg-2
      - mongodb-cfg-3
    mem_limit: 5G
    restart: always
    networks:
      shopline:
  mongodb-cfg-2:
    image: mongo:3
    expose:
      - 27019
    command: "mongod --configsvr --replSet mongodbcfg"
    links:
      - mongodb-router
      - mongodb-1
    mem_limit: 5G
    restart: always
    networks:
      shopline:
  mongodb-cfg-3:
    image: mongo:3
    expose:
      - 27019
    command: "mongod --configsvr --replSet mongodbcfg"
    links:
      - mongodb-router
      - mongodb-1
    mem_limit: 5G
    restart: always
    networks:
      shopline:
  mongodb-1:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-1"
    volumes:
      - ./mnt/data/mongo1:/data/db
    mem_limit: 5G
    restart: always
    networks:
      shopline:
  mongodb-2:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-1"
    volumes:
      - ./mnt/data/mongo2:/data/db
    mem_limit: 5G
    restart: always
    networks:
      shopline:
  mongodb-3:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-1"
    volumes:
      - ./mnt/data/mongo3:/data/db
    mem_limit: 5G
    restart: always
    networks:
      shopline:
  mongodb-4:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-2"
    volumes:
      - ./mnt/data/mongo4:/data/db
    mem_limit: 5G
    restart: always
    networks:
      shopline:
  mongodb-5:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-2"
    volumes:
      - ./mnt/data/mongo5:/data/db
    mem_limit: 5G
    restart: always
    networks:
      shopline:
  mongodb-6:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard-2"
    volumes:
      - ./mnt/data/mongo6:/data/db
    mem_limit: 5G
    restart: always
    networks:
      shopline:
  mongodb-router:
    image: mongo:3
    ports:
      - 27017:27017
    command: "mongos --configdb mongodbcfg/mongodb-cfg-1:27019,mongodb-cfg-2:27019,mongodb-cfg-3:27019"
    mem_limit: 5G
    restart: always
    networks:
      shopline:
        aliases:
          - dev-mongo
    labels:
      kompose.service.type: LoadBalancer

networks:
  shopline:
