version: '2'
services:
  mongodb-cfg-1:
    image: mongo:3
    expose:
      - 27019
    command: "mongod --configsvr --replSet mongodbcfg"
    links:
      - mongodb-router
      - mongodb-1
      - mongodb-cfg-2
      - mongodb-cfg-3
  mongodb-cfg-2:
    image: mongo:3
    expose:
      - 27019
    command: "mongod --configsvr --replSet mongodbcfg"
    links:
      - mongodb-router
      - mongodb-1
  mongodb-cfg-3:
    image: mongo:3
    expose:
      - 27019
    command: "mongod --configsvr --replSet mongodbcfg"
    links:
      - mongodb-router
      - mongodb-1
  mongodb-1:
    image: mongo:3
    expose:
      - 27018
    links:
      - mongodb-2
      - mongodb-3
    command: "mongod --shardsvr --replSet mongodbshard"
  mongodb-2:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard"
  mongodb-3:
    image: mongo:3
    expose:
      - 27018
    command: "mongod --shardsvr --replSet mongodbshard"
  mongodb-router:
    image: mongo:3
    expose:
      - 27017
    command: "mongos --configdb mongodbcfg/mongodb-cfg-1:27019,mongodb-cfg-2:27019,mongodb-cfg-3:27019"
    labels:
      kompose.service.type: LoadBalancer
